builds:
  - id: wombat
    main: cmd/wombat/main.go
    binary: wombat
    goos: [ windows, darwin, linux, freebsd, openbsd ]
    goarch: [ amd64, arm, arm64 ]
    goarm: [ 6, 7 ]
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm
    env:
      - CGO_ENABLED=0
    ldflags: >
      -s -w
      -X github.com/wombatwisdom/wombat/internal/cli.Version={{.Version}}
      -X github.com/wombatwisdom/wombat/internal/cli.DateBuilt={{.Date}}
archives:
  - id: wombat
    builds: [ wombat ]
    format: tar.gz
    files:
      - README.md
      - CHANGELOG.md
      - LICENSE
dist: target/dist
release:
  github:
    owner: wombatwisdom
    name: wombat
  prerelease: auto
  disable: false
