version: 2
project_name: wombat

env:
  - GO111MODULE=on

git:
  tag_sort: -version:creatordate
  prerelease_suffix: "-"

before:
  hooks:
    - go mod tidy
    - task check:license  # Keep the license check

builds:
  - id: wombat
    main: ./cmd/wombat
    binary: wombat
    env:
      - CGO_ENABLED=0
    ldflags:
      - -w -s
      - -X main.Version={{.Version}}
      - -X main.DateBuilt={{.Date}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

  - id: wombat-mqclient
    main: ./cmd/wombat
    binary: wombat
    env:
      - CGO_ENABLED=1
      - CGO_CFLAGS={{ if index .Env "CGO_CFLAGS" }}{{ .Env.CGO_CFLAGS }}{{ else }}-I/opt/mqm/inc{{ end }}
      - CGO_LDFLAGS={{ if index .Env "CGO_LDFLAGS" }}{{ .Env.CGO_LDFLAGS }}{{ else }}-L/opt/mqm/lib64{{ end }}
      - CGO_LDFLAGS_ALLOW={{ if index .Env "CGO_LDFLAGS_ALLOW" }}{{ .Env.CGO_LDFLAGS_ALLOW }}{{ else }}-Wl,-rpath.*{{ end }}
    flags:
      - -tags=mqclient
    ldflags:
      - -w -s
      - -X main.Version={{.Version}}
      - -X main.DateBuilt={{.Date}}
    goos:
      - linux
    goarch:
      - amd64

archives:
  - id: wombat-stub
    builds:
      - wombat
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

  - id: wombat-mqclient
    builds:
      - wombat-mqclient
    name_template: >-
      {{ .ProjectName }}-mqclient_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

dockers:
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/wombat:{{ .Tag }}"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/wombat:v{{ .Major }}"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/wombat:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/wombat:latest"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64,linux/arm64"
      - "--push"

changelog:
  use: github
  sort: asc
  groups:
    - title: '✨ Features'
      regexp: '^feat(\(.+\))?: .+'
      order: 0
    - title: '🐛 Bug Fixes'
      regexp: '^fix(\(.+\))?: .+'
      order: 1
    - title: '📚 Documentation'
      regexp: '^docs?(\(.+\))?: .+'
      order: 2
    - title: '🧪 Testing'
      regexp: '^test(\(.+\))?: .+'
      order: 3
    - title: '🔨 Refactoring'
      regexp: '^refactor(\(.+\))?: .+'
      order: 4
    - title: 'Other Changes'
      order: 999
  filters:
    exclude:
      - '^Merge pull request'
      - '^Merge branch'