name: Integration Test

on:
  schedule:
    - cron: '0 1 * * *' # run at 1 AM UTC

jobs:
  integration-test:
    if: ${{ github.repository == 'wombatwisdom/wombat' || github.event_name != 'schedule' }}
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
    steps:

    - name: Checkout code
      uses: actions/checkout@v5

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.4
        check-latest: true

    - name: Setup go-task / task / taskfile
      uses: rnorton5432/setup-task@v1

    - name: Deps
      run: |
        task deps
        if ! git diff-index --quiet HEAD; then
          echo "::error::Stale go.{mod,sum} detected. This can be fixed with 'task deps'."
          echo "::group::git diff go.mod"
          git diff go.mod || true
          echo "::endgroup::"
          echo "::group::git diff go.sum"
          git diff go.sum | head -100 || true
          echo "::endgroup::"
          exit 1
        fi

    - name: Integration Test
      run: go test -run "^Test.*Integration$" -timeout 60m ./...
